services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: [ "5432:5432" ]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
  redis:
    image: redis:7
    restart: unless-stopped
    ports: [ "6379:6379" ]
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports: [ "8025:8025" ]
volumes:
  pgdata:
