name: CD - Web
on:
  push:
    branches: [ main ]
    paths:
      - 'apps/web/**'
      - '.github/workflows/cd-web.yml'
jobs:
  deploy-web:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - name: Deploy to Vercel (if configured)
        if: ${{ secrets.VERCEL_TOKEN != '' }}
        run: |
          npm i -g vercel@latest
          cd apps/web
          vercel pull --yes --environment=production --token "${{ secrets.VERCEL_TOKEN }}"
          vercel build --prod --token "${{ secrets.VERCEL_TOKEN }}"
          vercel deploy --prebuilt --prod --token "${{ secrets.VERCEL_TOKEN }}"
