# .github/workflows/context-snapshot.yml
name: Context Snapshot
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: corepack enable
      - run: pnpm -v || npm i -g pnpm
      - run: pnpm -w add -D yaml glob
      - run: node tools/context-snapshot.mjs
      - name: Commit snapshot
        run: |
          if [ -n "$(git status --porcelain docs/CONTEXT_SNAPSHOT.md)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/CONTEXT_SNAPSHOT.md
            git commit -m "docs(context): atualizar CONTEXT_SNAPSHOT.md"
            git push
          else
            echo "Nada a atualizar."
          fi
